
[libraries]
commons-lang = "org.apache.commons:commons-lang3:3.12.0"
spring-boot-starter-web = "org.springframework.boot:spring-boot-starter-web:3.1.4"
flyway-core = "org.flywaydb:flyway-core:9.22.2"


